#!/usr/bin/env ruby

require File.dirname(__FILE__) + '/../config/environment'

TweetStream.configure do |config|
  config.consumer_key       = ENV['TWITTER_CONSUMER_KEY']
  config.consumer_secret    = ENV['TWITTER_CONSUMER_SECRET']
  config.oauth_token        = ENV['TWITTER_OAUTH_TOKEN']
  config.oauth_token_secret = ENV['TWITTER_OAUTH_TOKEN_SECRET']
  config.auth_method        = :oauth
end

TweetStream::Client.new.track(ENV['TRACK_HASHTAG']) do |tweet|
  begin
    Story.create_from_tweet(tweet)
    print '.'
  rescue ActiveRecord::RecordInvalid
    puts "Problem with tweet #{tweet.id}"
  end
end
